from .carrera import Carrera
from .materia import Materia
from .profesor import Profesor
from .estudiante import Estudiante
from .aula import Aula
from .grupo import Grupo
from .bloque_horario import BloqueHorario
from .dia_semana import DiaSemana
from .periodo_evaluacion import PeriodoEvaluacion
from .tipo_evaluacion import TipoEvaluacion
from .horario_clase import HorarioClase
from .examen import Examen
from .examen_sinodales import ExamenSinodales
from .examen_alumnos import ExamenAlumno
